### ISSUE TITLE
List all text runs

### ISSUE THREAD

**Issue by tobiasandersen** [rive-app/rive-wasm#371] opened 2024-10-23 14:39 UTC
We're building a UI for interacting with Rive graphics (that aren't built by us), and we want to automatically expose all inputs and text runs to the user. Currently we can easily detect which inputs are available with the `stateMachineInputs()` method — but I don't think it's possible to do for text runs?

It would be fantastic to have a similar method for retrieving text runs, e.g. `textRuns()`. Alternatively https://github.com/rive-app/rive-wasm/issues/359 could also work for us, but I still think this method makes sense.

**Comment by HayesGordon** [comment] 2024-11-04 09:32
Closing this as a duplicate of #359. I'll provide more information there.

**Closed as completed by HayesGordon** 2024-11-04 09:32 UTC
